<?
    /**
     * Author: Cel Ticó Petit
     *
     * Company: Cencis s.c.p.
     * Contact: cel@cenics.net
     */
    $this->headTitle('Qu CKEditor');
?>
    <textarea id="editor"></textarea>
<?
    $this->QuCkEditor(
        'editor',
            array('Width' => "100%",
                 'Height' => "340",
                 'toolbar'=> array(
                     array('Source','Maximize'),
                     array('Templates','Styles','Format'),
                     array('Bold','Italic','Underline','Subscript','Superscript'),
                     array('NumberedList','BulletedList','Outdent','Indent'),
                     array('JustifyLeft','JustifyCenter','JustifyRight'),
                     array('Link','Unlink'),
                     array('Image','Table')
                 )
            )
    );
?>
